import sys
import os
import subprocess
import argparse
from argparse import Namespace

import pandas as pd

from rich import print as rprint
from rich.status import Status
from typing import List, Tuple, Dict
from multiprocessing import Pool

from pathlib import Path
import pathlib
import glob

from pathlib import Path
src_path = Path(__file__).parent.resolve()
sys.path.append(str(src_path))

from rdkit import Chem
from rdkit.Chem.rdmolfiles import SDMolSupplier as _SDF
from rdkit.Chem.rdchem import Mol as _MOL

class GetGlideSelectPose():
    def __init__(self, rootpath: str, fps: List[pathlib.PosixPath], ids: List[str]) -> None:
        self.rootpath: str = rootpath
        self.jobs: List[pathlib.PosixPath] = fps

        self.ids: List[str] = ids
        self.s_mols: List[List[_MOL]] = None

    def handle_one_job(self, fname: str):
        id1: str = None
        id2: str = None
        sd: _SDF  = Chem.SDMolSupplier(fname, sanitize=False, removeHs=False)            # sanitize=False, 避免不必要的错误
        mols: List[Dict] = []
        for i,  i_mol in enumerate(sd):
            if not i_mol:
                rprint("Error[iawnix]:sdf read mol\n\t{}, {}".format(fname, i_mol))
                continue
            if i != 0:
                id1 = i_mol.GetProp("s_lp_Variant").split("-")[0]
                id2 = i_mol.GetProp("_Name")
                if  id1 == id2 and id2 in self.ids:
                    i_score = i_mol.GetProp("r_i_docking_score")
                    var_i: Dict = {"mol":i_mol, "id":id2, "score":i_score}
                    mols.append(var_i)
        
        # 这里将获取的分子保存出来
        
        return mols

    def multrun(self, num_cpu: int) -> None:
        pool = Pool(num_cpu)
        self.s_mols = pool.map(self.handle_one_job, self.jobs)
        pool.close()
        pool.join()


def Parm() -> Namespace:
    """
        -InFiles: inroot: xx.sdf
                     xx.sdf
                     ...
    """

    parser = argparse.ArgumentParser(description=
                                     "The author is very lazy and doesn't want to write anything\n"
                                     "Author: Xiao He [ECNU]")

    parser.add_argument("-InFiles",type=str, nargs=1, default = None,help="FilePaths: The directory for storing SDF files generated by ExportDockPose.")
    parser.add_argument("-SelectID",type=str, nargs=1, default = None,help="SelectID File[csv]: The provided file must be in `CSV` format and contain a required `ID` field.")
    parser.add_argument("-cpu",type=int, nargs=1, default = 1,help="The number of the cpus")
    parser.add_argument("-output",type=str, nargs=1, default = "SelectGlidePose.sdf",help="SaveFile: `SDF` format")
    parser.add_argument("-verbose",type=bool, nargs=1, default = False,help="Enable detailed output: True / False")

    return parser.parse_args()


def check_SelctIDFile(dat: pd.DataFrame) -> bool:
    if "ID" not in dat.columns:
        return False
    else:
        return True

def main() -> None:

    fps: List[pathlib.PosixPath] = []
    rootpath: str = os.getcwd()
    logtype: str = None
    id_csv:  pathlib.PosixPath = None
    select_id: List[str] = []
    myP = Parm()

    # 读取需要
    id_csv = Path(myP.SelectID[0]).absolute()
    # 这里需要读取两个字段, 一个是id, 一个是FP_NAME, 其中FP_NAME只有basename
    # 首先对FP_NAME进行分组
    selectIDDat = pd.read_csv(id_csv)
    if not check_SelctIDFile(selectIDDat):
        print("Error[iaw]:> The provided file must be in `CSV` format and contain a required `ID` field.")
        sys.exit(-1)
    
    select_id = list(set(selectIDDat["ID"]))
    inroot: pathlib.PosixPath = Path(myP.InFiles[0]).absolute()
    fps.extend([Path(_f).absolute() for _f in glob.glob("{}/*.sdf".format(inroot.as_posix()))])
    
    # init savePath
    savePath: pathlib.PosixPath = Path(myP.output[0]).absolute()
    with Status("Running...", spinner = "pong") as status:
        myjob = GetGlideSelectPose(rootpath=rootpath,
                      fps=fps
                      ,ids=select_id)
        myjob.multrun(num_cpu=myP.cpu[0])

    select_pose: List[_MOL] = []
    for var in myjob.s_mols:
        select_pose.extend(var)

    if myP.verbose[0] == True:
        rprint(select_id)
        rprint(select_pose)
    
    n_select_pose: int = len(select_pose)

    writer = Chem.SDWriter(savePath)
    for mol in select_pose:
        if not mol:
            print("Error[iaw]:mol writer\n\t{}".format(mol))
            continue
        i_mol = mol["mol"]
        i_mol.SetProp("_Name", mol["id"])
        i_mol.SetProp("r_i_docking_score", mol["score"])
        #_id: str =  mol.GetProp("_Name")
        writer.write(i_mol)

if __name__ == "__main__":
    main()

